# Generated by Django 3.2.19 on 2023-06-02 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0003_useraddress_usercart_userorder_userorderitem_userreview_userwishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': 'User Address', 'verbose_name_plural': 'User Addresses'},
        ),
        migrations.AlterModelOptions(
            name='userorder',
            options={'verbose_name': 'User Order', 'verbose_name_plural': 'User Orders'},
        ),
        migrations.AlterModelOptions(
            name='userorderitem',
            options={'verbose_name': 'User Order Item', 'verbose_name_plural': 'User Order Items'},
        ),
        migrations.AlterModelOptions(
            name='userotp',
            options={'verbose_name': 'User OTP', 'verbose_name_plural': 'User OTPs'},
        ),
    ]
