# Generated by Django 3.2.19 on 2023-05-30 04:28

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_auto_20230529_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAttributeMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.attribute')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.category')),
            ],
            options={
                'verbose_name': 'Category Attribute Map',
                'verbose_name_plural': 'Category Attribute Maps',
                'ordering': ['category', 'attribute'],
                'unique_together': {('category', 'attribute')},
            },
        ),
    ]
