# Generated by Django 3.2.19 on 2023-05-30 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_categoryattributemap'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEcommercePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('platform', models.CharField(choices=[('amazon', 'Amazon'), ('flipkart', 'Flipkart')], max_length=50)),
                ('url', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productapp.product')),
            ],
            options={
                'verbose_name': 'Product Ecommerce Platform',
                'verbose_name_plural': 'Product Ecommerce Platforms',
                'ordering': ['product', 'platform'],
                'unique_together': {('product', 'platform')},
            },
        ),
    ]
