# Generated by Django 3.2.19 on 2023-05-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0004_productecommerceplatform'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributemap',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
