# Generated by Django 3.2.19 on 2023-06-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_productattributemap_is_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='categoryattributemap',
            options={'verbose_name': 'Category Attribute Map', 'verbose_name_plural': 'Category Attribute Maps'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productattributemap',
            options={'verbose_name': 'Product Attribute Map', 'verbose_name_plural': 'Product Attribute Maps'},
        ),
        migrations.AlterModelOptions(
            name='productecommerceplatform',
            options={'verbose_name': 'Product Ecommerce Platform', 'verbose_name_plural': 'Product Ecommerce Platforms'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='typeimage',
            options={'verbose_name': 'Type Image', 'verbose_name_plural': 'Type Images'},
        ),
        migrations.AddField(
            model_name='productecommerceplatform',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productecommerceplatform',
            name='platform',
            field=models.CharField(choices=[('ajio', 'Ajio'), ('amazon', 'Amazon'), ('flipkart', 'Flipkart'), ('meesho', 'Meesho'), ('myntra', 'Myntra'), ('nykaa', 'Nykaa'), ('tatacliq', 'Tata Cliq')], max_length=50),
        ),
    ]
